# Generated by Django 4.2 on 2023-06-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0002_alter_user1_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='space',
        ),
        migrations.AlterField(
            model_name='user1',
            name='comments',
            field=models.CharField(max_length=255),
        ),
    ]
