# Generated by Django 4.2 on 2023-06-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0003_remove_user1_space_alter_user1_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='images',
        ),
    ]
