# Generated by Django 4.2 on 2023-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0004_remove_user1_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='imagess',
            field=models.ManyToManyField(to='new1.image'),
        ),
    ]
