# Generated by Django 4.2 on 2023-06-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0007_remove_user1_imagess_delete_image_user1_imagess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='imagess',
            new_name='images1',
        ),
    ]
