# Generated by Django 4.2 on 2023-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0009_alter_user1_images1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='images1',
            field=models.ImageField(null=True, upload_to='media/new/images'),
        ),
    ]
