# Generated by Django 4.2 on 2023-06-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0010_alter_user1_images1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='space',
            field=models.IntegerField(default=0),
        ),
    ]
