# Generated by Django 4.2 on 2023-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0011_user1_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
