# Generated by Django 4.2 on 2023-07-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0012_user1_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='images1',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
