# Generated by Django 4.2 on 2023-07-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0014_alter_user1_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='rent',
            field=models.CharField(max_length=100),
        ),
    ]
